/**
* SpotrProjcetAPI
* SpotrProjcetAPI
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.ru.otus.kotlin.kmp.transport.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * упражнение его повторения, вес и подходы
 * @param nameExercise 
 * @param retry количество повторов
 * @param numberRepetitions количество повторений
 * @param ownWeight упражнение с своим весом?
 * @param weight вес в упражнении
 */
@Serializable
data class Exercise (
    @SerialName(value = "nameExercise")
    var nameExercise: kotlin.String = "NouName",
    /* количество повторов */
    @SerialName(value = "retry")
    var retry: kotlin.Int = 0,
    /* количество повторений */
    @SerialName(value = "numberRepetitions")
    var numberRepetitions: kotlin.Int = 0,
    /* упражнение с своим весом? */
    @SerialName(value = "OwnWeight")
    var ownWeight: kotlin.Boolean = true,
    /* вес в упражнении */
    @SerialName(value = "weight")
    var weight: kotlin.Int = 0
){
    companion object{
        val EmptyListExercise = listOf<Exercise>()
    }
}

