/**
* SpotrProjcetAPI
* SpotrProjcetAPI
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.ru.otus.kotlin.kmp.transport.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Данные при регистрации
 * @param login 
 * @param password 
 */
@Serializable
data class RegData (
    @SerialName(value = "login") var login: kotlin.String = "",
    @SerialName(value = "password") var password: kotlin.String = ""

){
    companion object{
        val EmpyRegData = RegData()
    }
}

