/**
* SpotrProjcetAPI
* SpotrProjcetAPI
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.ru.otus.kotlin.kmp.transport.models

import kotlinx.serialization.*

/**
 * Содержит описание тренеровки и упражнения
 * @param id 
 * @param name Название упражнения
 * @param description Описание упражнения
 * @param items 
 * @param workoutOuner 
 */
@Serializable
data class Workout (
    @SerialName(value = "id")
    var id: kotlin.String = "",
    /* Название упражнения */
    @SerialName(value = "name")
    var name: kotlin.String = "",
    /* Описание упражнения */
    @SerialName(value = "description")
    var description: kotlin.String = "",
    @SerialName(value = "items")
    var items: List<Exercise> = Exercise.EmptyListExercise,
    @SerialName(value = "workoutOuner")
    var workoutOuner: User = User.EmptyUser
)

