/**
* SpotrProjcetAPI
* SpotrProjcetAPI
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ModelForRequest.cruds

import ModelForRequest.ApiError
import ModelForRequest.ResponseWorkout
import kotlinx.serialization.*
import ru.ru.otus.kotlin.kmp.transport.models.BasePaginatedResponse

/**
 * Структура для ответа на запрос поиска объявлений
 * @param messageType 
 * @param result 
 * @param errors 
 * @param page 
 * @param foundAds 
 */
@Serializable
data class SearchWorkoutResponse (
    @SerialName(value = "messageType") override val messageType: kotlin.String? = null,
    @SerialName(value = "result") override val result: BaseResponse.Result? = null,
    @SerialName(value = "errors") override val errors: kotlin.collections.List<ApiError>? = null,
    @SerialName(value = "page") val page: BasePaginatedResponse? = null,
    @SerialName(value = "foundAds") val foundAds: kotlin.collections.List<ResponseWorkout>? = null
) : BaseMessage, BaseResponse

