/**
* SpotrProjcetAPI
* SpotrProjcetAPI
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ModelForRequest


import kotlinx.serialization.*

/**
* 
* Values: READ,UPDATE,DELITE
*/

@Serializable
enum class WorkoutPermissions(val value: kotlin.String) {


    @SerialName(value = "read")
    READ("read"),

    @SerialName(value = "update")
    UPDATE("update"),

    @SerialName(value = "delite")
    DELITE("delite");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

