/**
* SpotrProjcetAPI
* SpotrProjcetAPI
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ModelForRequest.cruds


import ModelForRequest.BasePaginatedRequest
import ModelForRequest.Debug
import kotlinx.serialization.*

/**
 * Структура для запроса поиска объявлений
 * @param messageType 
 * @param requestId 
 * @param debug 
 * @param page 
 */
@Serializable
data class SearchWorkoutRequest (
    @SerialName(value = "messageType") override val messageType: String? = null,
    @SerialName(value = "requestId") override val requestId: String? = null,
    @SerialName(value = "debug") override val debug: Debug? = null,
    @SerialName(value = "page") val page: BasePaginatedRequest? = null,
    @SerialName(value = "searchWorkoutId") val searchWorkoutId: String? = null

) : BaseMessage, BaseRequest

