openapi: 3.0.3
info:
  title: SpotrProjcetAPI
  description: SpotrProjcetAPI
  version: 0.0.1
servers:
  - url: http://localhost:8080
tags:
  - name: workout
    description: описание

paths:
  /workout/CreateRequest:
    post:
      tags:
        - workout
      requestBody:
        description: Запрос на создание workout(тренеровки)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkoutAddRequest"
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkoutAddResponse"

  /workout/create:
    post:
      tags:
        - workout
      requestBody:
        description: Объект запроса для инициализации при старте приложения
        content:
          application/json:
            schema:
#              $ref: "#/components/schemas/WorkoutTransfer"
        required: true
      responses:
        "201":
          description: workout has ben created
          content:
            application/json:
              schema:
#                $ref: "#/components/schemas/WorkoutTransfer"

  /workout:
    get:
      tags:
        - workout
      responses:
        200:
          description: все тренеровки
          content:
            application/json:
              schema:
                items:
                  type: array
                  items:
#                    $ref: "#/components/schemas/WorkoutTransfer"

  /workout/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: object
      tags:
        - workout
      responses:
        200:
          description: Показ тренеровки по ID
          content:
            application/json:
              schema:
#                $ref: "#/components/schemas/WorkoutTransfer"

    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: object
      tags:
        - workout
      responses:
        200:
          description: Удаление тренеровки по ID
          content:
            application/json:
              schema:
#                $ref: "#/components/schemas/WorkoutTransfer"

components:
  schemas:

    BaseMessage:
      type: object
      properties:
        messageType:
          type: string
      discriminator:
        propertyName: messageType

    BaseRequest:
      type: object
      properties:
        requestId:
          type: string
        debug:
          $ref: "#/components/schemas/Debug"

    BaseResponse:
      type: object
      properties:
        result:
          type: string
          enum:
            - success
            - error
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ApiError"

    ApiError:
      type: object
      properties:
        message:
          type: string
        field:
          type: string

    Debug:
      type: object
      properties:
        mode:
          type: string
          default:
            - prod
          enum:
            - prod
            - test
            - stub
        stub:
          type: string

    CreateWorkout:
      type: object
      title: Тренеровка
      description: Содержит описание тренеровки и упражнения
      properties:
        id:
          type: string
          description: id
        name:
          type: string
          description: Название упражнения
        description:
          type: string
          description: Описание упражнения
        items:
          type: array
          items:
            $ref: "#/components/schemas/ExerciseTransfer"

    UpdateWorkout:
      allOf:
        - $ref: "#/components/schemas/CreateWorkout"
        - type: object
          properties:
            id:
              type: string

    ResultWorkout:
      allOf:
        - $ref: "#/components/schemas/UpdateWorkout"
        - type: object
          properties:
            permissions:
              type: array
              items:
                $ref: "#/components/schemas/WorkoutPermissions"

    WorkoutPermissions:
      type: string
      enum:
        - read
        - update
        - delite

    WorkoutAddRequest:
      allOf:
        - $ref: "#/components/schemas/BaseMessage"
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            createWorkout:
              $ref: "#/components/schemas/CreateWorkout"
            debug:
              type: object
              properties:
                stub:
                  type: string
                  enum:
                    - success
                    - error


    WorkoutAddResponse:
      allOf:
        - $ref: "#/components/schemas/BaseMessage"
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            createdWorkout:
              $ref: "#/components/schemas/ResultWorkout"


    ExerciseTransfer:
      title: Упражнение
      type: object
      description: упражнение его повторения, вес и подходы
      properties:
        nameExercise:
          type: string
        retry:
          type: integer
          description: количество повторов
        numberRepetitions:
          type: integer
          description: количество повторений
        OwnWeight:
          type: boolean
          description: упражнение с своим весом?
        weight:
          type: integer
          description: вес в упражнении

    UserTransfer:
      title: Пользователь
      type: object
      description: Пользователь
      properties:
        id:
          type: object
        name:
          type: string
          description: Имя пользователя
        age:
          type: integer
          description: Возраст
        mass:
          type: integer
          description: Вес
        regData:
          type: object
          $ref: "#/components/schemas/RegDataTransfer"

    RegDataTransfer:
      title: Данные для регистрации
      type: object
      description: Данные при регистрации
      properties:
        login:
          type: string
        password:
          type: string



