openapi: 3.0.3
info:
  title: SpotrProjcetAPI
  description: SpotrProjcetAPI
  version: 0.0.1
servers:
  - url: http://localhost:8080
tags:
  - name: workout
    description: описание

paths:
  /workout/CreateRequest:
    post:
      tags:
        - workout
      requestBody:
        description: Запрос на создание workout(тренеровки)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutAdRequest'
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutAdResponse'

  /workout/create:
    post:
      tags:
        - workout
      requestBody:
        description: Объект запроса для инициализации при старте приложения
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutTransfer'
        required: true
      responses:
        '201':
          description: workout has ben created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutTransfer'

  /workout:
    get:
      tags:
        - workout
      responses:
        200:
          description: все тренеровки
          content:
            application/json:
              schema:
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/WorkoutTransfer'

  /workout/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: object
      tags:
        - workout
      responses:
        200:
          description: Показ тренеровки по ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutTransfer'

    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: object
      tags:
        - workout
      responses:
        200:
          description: Удаление тренеровки по ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutTransfer'

components:
  schemas:

    BaseMessage:
      type: object
      properties:
        messageType:
          type: string
      discriminator:
        propertyName: messageType

    BaseRequest:
      type: object
      properties:
        requestId:
          type: string
        debug:
          $ref: '#/components/schemas/Debug'

    Debug:
      type: object
      properties:
        mode:
          type: string
          default:
            - prod
          enum:
            - prod
            - test
            - stub
        stub:
          type: string

    CreateAd:
      type: object
      properties:
        title:
          type: string
          description: "Заголовок тренеровки"


    WorkoutAdRequest:
      type: object



    WorkoutAdResponse:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            createAd:
              $ref:




    WorkoutTransfer:
      title: Тренеровка
      description: Содержит описание тренеровки и упражнения
      type: object
      properties:
        id:
          type: object
        name:
          type: string
          description: Название упражнения
        description:
          type: string
          description: Описание упражнения
        items:
          type: array
          items:
            $ref: '#/components/schemas/ExerciseTransfer'
        workoutOuner:
          type: object
          $ref: '#/components/schemas/UserTransfer'


    ExerciseTransfer:
      title: Упражнение
      type: object
      description: упражнение его повторения, вес и подходы
      properties:
        nameExercise:
          type: string
        retry:
          type: integer
          description: количество повторов
        numberRepetitions:
          type: integer
          description: количество повторений
        OwnWeight:
          type: boolean
          description: упражнение с своим весом?
        weight:
          type: integer
          description: вес в упражнении

    UserTransfer:
      title: Пользователь
      type: object
      description: Пользователь
      properties:
        id:
          type: object
        name:
          type: string
          description: Имя пользователя
        age:
          type: integer
          description: Возраст
        mass:
          type: integer
          description: Вес
        regData:
          type: object
          $ref: '#/components/schemas/RegDataTransfer'

    RegDataTransfer:
      title: Данные для регистрации
      type: object
      description: Данные при регистрации
      properties:
        login:
          type: string
        password:
          type: string



